### ISSUE TITLE
Support for google.dk

### ISSUE THREAD

**Issue by LinuxSan** [CodyMcCodington/AutoCookieOptout#18]
Hi
Is it possible to add support for google.dk?

**Comment by CodyMcCodington** [comment]
Yep, it's coming up in the 0.7 release 😎
https://github.com/CodyMcCodington/AutoCookieOptout/pull/19

**Comment by CodyMcCodington** [comment]
I've submitted the 0.7 release to Mozilla. The change will roll out automatically after Mozilla approves the new version.
