### ISSUE TITLE
Support for google.co.uk

### ISSUE THREAD

**Issue by StevenEddies** [CodyMcCodington/AutoCookieOptout#23]
**Describe the bug**
The plugin does not auto-optout of cookies on Google's UK domains. Would it be possible to add support for these please?

**Reproduction steps**
* Open a private browsing window
* Navigate to https://www.google.co.uk/ or https://maps.google.co.uk/
* Observe Google's optout popup remains open

**Expected behavior**
I expected the plugin to close the popup by automatically opting out (as it does on https://www.google.com/ in the same browser)

**Specifications:**
- OS: Linux Mint 19.3
- Firefox version: 96.0
- Auto Cookie Optout version: 0.7

**Comment by CodyMcCodington** [comment]
I'll investigate it and fix it in the upcoming 0.8 release. Thanks for reporting!

**Comment by CodyMcCodington** [comment]
I was able to reproduce the problem on both URLs. Both are now working fine for me following the 0.8 update we just shipped.

**Comment by StevenEddies** [comment]
Thanks for the fix and the quick turnaround, can confirm it's working for me now
