### ISSUE TITLE
Add on not available/installable on Firefox for Android

### ISSUE THREAD

**Issue by Iolaum** [CodyMcCodington/AutoCookieOptout#24]
Not sure if this is intended or not.

Would be awesome if this was available for firefox on android.

**Comment by bertvandepoel** [comment]
If I recall correctly, only a very small number of addons have been cleared by Mozilla for use on Firefox for Android. I'm not even sure if it's something you can apply for or not. Perhaps you could look into this and report back, @Iolaum? That way, not all the pressure is on the maintainer of this addon :)

**Comment by CodyMcCodington** [comment]
@bertvandepoel is correct: Mozilla currently limits the availability of extensions on Firefox for Android.

If you're adventurous, they do provide a well-hidden workaround in Firefox Nightly.

- Go to 'Settings'
- Go to 'About Firefox Nightly'
- Tap the logo a couple of times to activate the debug menu
- Go back to the 'Settings' menu
- Under 'Custom Add-on collection', enter values '16884442' and 'ACO-Android'

I have been using this on my phone for a while and it seems to work, except on a specific Google consent page that only seems to show up on mobile. Keep in mind that Firefox Nightly may be unstable and Auto Cookie Optout isn't officially supported on Android, so your mileage may vary. But you're definitely welcome to try it :)

If Mozilla's policy on this changes, feel free to reopen the thread.
